# Generated by Django 4.2.5 on 2023-11-02 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('settlement_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='FederalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, null=True)),
                ('municipality_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('zip_code', models.PositiveIntegerField()),
                ('locality', models.CharField(max_length=200)),
                ('federal_entity_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.federalentity')),
            ],
        ),
    ]
