# Generated by Django 4.2.5 on 2023-11-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalentity',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
