# Generated by Django 4.2.5 on 2023-11-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_federalentity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalentity',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='key',
            field=models.CharField(max_length=20),
        ),
    ]
